# Generated by Django 5.2.3 on 2025-07-01 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=30, unique=True)),
                ('dish_type', models.CharField(choices=[('CH', 'Chicken'), ('PO', 'Pork'), ('SF', 'Sea Food'), ('VE', 'Vegerables')], max_length=3)),
                ('dish_method', models.CharField(choices=[('SAUTE', 'Saute'), ('STIRFY', 'Stirfry'), ('FRIED', 'Fried'), ('BAKED', 'Baked'), ('SAUCY', 'Saucy'), ('SOUPY', 'Soupy')], max_length=10)),
                ('dish_color', models.CharField(blank=True, choices=[('O/R', 'Orange/Red'), ('BR', 'Brown'), ('OR', 'Orange'), ('WH', 'White')], max_length=4)),
                ('dish_description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_menus', to='api.dish')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_dishes', to='api.menu')),
            ],
        ),
    ]
