# Generated by Django 5.2.3 on 2025-07-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_method',
            field=models.CharField(choices=[('SAUTE', 'Saute'), ('STIRFY', 'Stirfry'), ('FRIED', 'Fried'), ('BAKED', 'Baked'), ('SAUCY', 'Saucy'), ('SOUPY', 'Soupy'), ('ROASTED', 'Roasted')], max_length=10),
        ),
    ]
