# Generated by Django 5.2.3 on 2025-07-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dish_dish_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_calories',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_color',
            field=models.CharField(blank=True, choices=[('BR', 'Brown'), ('OR', 'Orange'), ('WH', 'White'), ('YE', 'Yellow')], max_length=4),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_method',
            field=models.CharField(blank=True, choices=[('SAUTE', 'Saute'), ('STIRFY', 'Stirfry'), ('FRIED', 'Fried'), ('BAKED', 'Baked'), ('SAUCY', 'Saucy'), ('SOUPY', 'Soupy'), ('ROASTED', 'Roasted')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_type',
            field=models.CharField(choices=[('CH', 'Chicken'), ('PO', 'Pork'), ('SF', 'Sea Food'), ('VE', 'Vegerables'), ('BF', 'Breakfast'), ('SN', 'Snacks'), ('FR', 'Fruits')], max_length=3),
        ),
    ]
