# Generated by Django 5.2.3 on 2025-07-24 04:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dish_dish_calories_alter_dish_dish_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('student_number', models.CharField(max_length=11)),
                ('up_mail', models.EmailField(max_length=50)),
                ('dish_name', models.CharField(max_length=30)),
                ('dish_type', models.CharField(choices=[('CH', 'Chicken'), ('PO', 'Pork'), ('SF', 'Sea Food'), ('VE', 'Vegerables'), ('BF', 'Breakfast'), ('SN', 'Snacks'), ('FR', 'Fruits')], max_length=3)),
                ('dish_description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, unique=True),
        ),
    ]
