# Generated by Django 5.2.3 on 2026-01-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_request_alter_menu_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_dislikes',
            field=models.PositiveBigIntegerField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_likes',
            field=models.PositiveIntegerField(default=0, max_length=6),
        ),
    ]
