# Generated by Django 5.2.3 on 2026-01-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dish_dish_dislikes_dish_dish_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_dislikes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
