# Generated by Django 5.2.3 on 2026-01-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_dish_dish_dislikes_alter_dish_dish_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='dish_dislikes',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='dish_likes',
        ),
    ]
