# Generated by Django 5.2.3 on 2026-01-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_dish_dish_dislikes_remove_dish_dish_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
